### ISSUE TITLE
Soyuz/Vostok/Voskhod Parachutes

### ISSUE THREAD

**Issue by wm1248** [KSP-RO/SovietSpacecraft#3]
Updated KSP to 1.2, installed the latest mod update. Parachutes no longer show up in the staging list nor deploy. Part can be highlighted, but no menu on right click. Squad parachutes work as they should

**Comment by raidernick** [comment]
First off, they work perfectly fine on a clean game with only my mod and required mods installed. Proof below.
![alt tag](http://i.imgur.com/YN0mYDy.png)

Second, if you installed with CKAN, don't even reply to this post until you've done a manual install on a clean game with no other mods at all and confirmed that then and only then it doesn't work. I provide ZERO support for CKAN, my mod posts clearly say this....

After doing that, if it still doesn't work, I still can't help you because it works fine for me and everyone else, I can't replicate it, and it has to be a mod conflict on your end.
